name: Java CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: 'SquareTrinomial'
        run:
          cd ./4.1.1;
          mvn -B clean compile test install;
          cd ../
      
      - name: 'SquareTrinomialMaxRootExtractor'
        run:
          cd ./4.1.2;
          mvn -B clean compile test;
          cd ../
      
      - name: 'ParameterizedClasses (functions)'
        run:
          cd ./4.2;
          mvn -B clean compile test;
          cd ../
      
      - name: 'Products (dependency)'
        run:
          cd ./3.1;
          mvn -B clean install;
          cd ../
      
      - name: 'Comparators'
        run:
          cd ./4.3;
          mvn -B clean compile test;
          cd ../
